name: CI

# Use this workflow whenever there is a push or pull request on the "ci-cd/github-actions" branch
on:
  push:
    branches: [ ci-cd/github-actions ]
  pull_request:
    branches: [ ci-cd/github-actions ]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update system
        run: sudo apt update
      - name: Install GCC/G++ Multilib
        run: sudo apt install -y gcc-multilib g++-multilib
      - name: Build
        run: cd linux && CFG=release make
      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: Linux-x86
          path: |
            linux/release/client.so
            linux/release/client.so.dbg
            linux/release/hl.so
            linux/release/hl.so.dbg
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: MSBuild.exe projects/vs2019/projects.sln /p:Configuration=Release /p:Platform=Win32
      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: Win32
          path: |
            projects/vs2019/Release/client/client.dll
            projects/vs2019/Release/client/client.exp
            projects/vs2019/Release/client/client.lib
            projects/vs2019/Release/client/client.pdb
            projects/vs2019/Release/hl/hl.dll
            projects/vs2019/Release/hl/hl.exp
            projects/vs2019/Release/hl/hl.lib
            projects/vs2019/Release/hl/hl.pdb